### ISSUE TITLE
add generalized currency indicators

### ISSUE THREAD

**Issue by sidnym-ladrut** [tocwex/fund#83]
With the changes in #70, project targets will no longer necessarily be denominated in U.S. dollars, and the user interface needs to be updated in a variety of places to reflect this:

- [x] Project view/listing headers (e.g. "Goal: $10")
- [x] Funding thermometers (e.g. "$2 funded")
- [x] Project submission form (e.g. "milestone budget ($)")
- [x] Funder contribution/pledge cards (e.g. "~sampel-palnet donated $2")

**Comment by thelifeandtimes** [comment]
Open Question (not urgent):
- As we go to supporting generalized token support, do we want to manually support new tokens (just raw pulling them in and putting them into a manually upkept list? I assume this is the path we will go at first, but what would it mean to pull in data from elsewhere? how would people request additional token support?

**Comment by sidnym-ladrut** [comment]
> * As we go to supporting generalized token support, do we want to manually support new tokens (just raw pulling them in and putting them into a manually upkept list? I assume this is the path we will go at first, but what would it mean to pull in data from elsewhere? how would people request additional token support?

At first we'll just support a static list, but we do want to ultimately add an option for "any contract supporting the ERC-20 standard." If certain coins are used frequently enough, we could even detect this at the blockchain level and integrate them into the app as defaults.

**Comment by thelifeandtimes** [comment]
Ok, so my thinking on this is as follows:

We have 3 mechanisms for indicating the currency in which an amount is denominated:
 - text/unicode characters, i.e. `$` or `Ξ`
 - Tickers, i.e `$WSTR` or `$USDC`
 - Token Icons

Not every token has immediately recognizable unicode characters (no wrapped star unicode, yet), Tickers are long, and Token Icons are really annoying if we drop them absolutely everywhere.

My proposed solution, since we will be doing initial maintenance of the list manually, is to use the unicode characters when available as prefixes, i.e. `Ξ 1.4797` or `$3,137`, and then tickers as suffixes if there is no unicode, i.e. `12.21 $WSTR` or `123,324,678 $PEPE`. The token icons are then used very sparingly, for example in the following places:
- on the token selection dropdown in the contribute modal (yes, this is deliberately a dropdown with a single, pre-selected option)
- on the project card
- on the project creation page (somewhat excessively here, but we wan't someone to not accidentally fuck up in that context.)

**Comment by sidnym-ladrut** [comment]
@thelifeandtimes: I think this is completed; feel free to reopen if not.
